import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const sans=Geist({variable:"--font-geist-sans",subsets:["latin"]}); const mono=Geist_Mono({variable:"--font-geist-mono",subsets:["latin"]});
export const metadata:Metadata={title:"BestAIAgent.in — Find and Compare AI Agents with Evidence",description:"Discover and compare AI agents with transparent scoring, source-backed claims, INR pricing context, deployment options, and India Fit analysis.",keywords:["best AI agents","AI agent directory","compare AI agents","AI agents India","AI agent marketplace"],openGraph:{title:"BestAIAgent.in — Evidence-led AI Agent Discovery",description:"Find the right AI agent with transparent scores, evidence, and India-specific context.",type:"website",locale:"en_IN"},twitter:{card:"summary_large_image",title:"BestAIAgent.in",description:"Evidence-led AI agent discovery for India and the world."},alternates:{canonical:"https://bestaiagent.in/"},robots:{index:true,follow:true},other:{"codex-preview":"development"},icons:{icon:"/favicon.svg",shortcut:"/favicon.svg"}};
const org={"@context":"https://schema.org","@type":"Organization","@id":"https://bestaiagent.in/#organization",name:"BestAIAgent.in",url:"https://bestaiagent.in/",description:"Independent AI agent discovery and evaluation platform."};
const site={"@context":"https://schema.org","@type":"WebSite","@id":"https://bestaiagent.in/#website",url:"https://bestaiagent.in/",name:"BestAIAgent.in",publisher:{"@id":"https://bestaiagent.in/#organization"},potentialAction:{"@type":"SearchAction",target:"https://bestaiagent.in/?q={search_term_string}","query-input":"required name=search_term_string"}};
const article={"@context":"https://schema.org","@type":"Article",headline:"Best AI Agents 2026: Evidence-led rankings and India Fit analysis",datePublished:"2026-08-14","dateModified":"2026-08-14",author:{"@type":"Organization",name:"BestAIAgent.in"},publisher:org,description:"Comprehensive evidence-backed guide to the best AI agents in 2026, with editorial scores, India Fit ratings, pricing context, and deployment analysis."};
const speakable={"@context":"https://schema.org","@type":"SpeakableSpecification",cssSelector:["h1","[data-direct-answer]"]};
const faq={"@context":"https://schema.org","@type":"FAQPage",mainEntity:[{"@type":"Question",name:"What is an AI agent?","acceptedAnswer":{"@type":"Answer",text:"An AI agent is an autonomous software system that perceives its environment, makes decisions, and takes actions to achieve specific goals — from coding and research to voice and enterprise workflows."}},{"@type":"Question",name:"How are BestAIAgent.in scores calculated?","acceptedAnswer":{"@type":"Answer",text:"Scores are editorial assessments based on verified evidence: official documentation, pricing, hands-on testing, India Fit signals (INR pricing, language, deployment, compliance), and source-backed claims with retrieval dates."}},{"@type":"Question",name:"Are the rankings pay-to-rank?","acceptedAnswer":{"@type":"Answer",text:"No. BestAIAgent.in does not accept payment for ranking. Every score references primary sources, and the methodology is fully published for transparency."}}]};
const data={"@context":"https://schema.org","@graph":[org,site,article,speakable,faq]};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en-IN"><body className={`${sans.variable} ${mono.variable}`}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>{children}</body></html>}
